"""add colecao_id to Filme

Revision ID: f815c30fe81c
Revises: 
Create Date: 2025-06-19 18:25:24.969667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f815c30fe81c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colecao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_filme_colecao', 'colecao', ['colecao_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('colecao_id')

    # ### end Alembic commands ###
